# Generated by Django 6.0.7 on 2026-10-03 01:02

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculo', '0003_conteudo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoConteudo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('youtube_id', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9_-]{11}$', 'Identificador do YouTube inválido.')])),
                ('titulo', models.CharField(max_length=255)),
                ('canal_nome', models.CharField(max_length=255)),
                ('canal_url', models.URLField(max_length=500)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('duracao_segundos', models.PositiveIntegerField(blank=True, null=True)),
                ('nota_curador', models.TextField(blank=True)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('metadados_atualizados_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('conteudo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='curriculo.conteudo')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='videos_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'vídeo de conteúdo',
                'verbose_name_plural': 'vídeos de conteúdo',
                'ordering': ['ordem', 'criado_em'],
            },
        ),
        migrations.CreateModel(
            name='SessaoVideo',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('inicio_segundos', models.PositiveIntegerField()),
                ('fim_segundos', models.PositiveIntegerField()),
                ('segundos_assistidos', models.PositiveIntegerField()),
                ('percentual_video', models.DecimalField(decimal_places=2, max_digits=5)),
                ('iniciado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_video', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes', to='videos.videoconteudo')),
            ],
            options={
                'verbose_name': 'sessão de vídeo',
                'verbose_name_plural': 'sessões de vídeo',
                'ordering': ['-iniciado_em'],
            },
        ),
        migrations.CreateModel(
            name='ProgressoVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('segmentos_assistidos', models.JSONField(blank=True, default=list)),
                ('percentual', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ultima_posicao_segundos', models.PositiveIntegerField(default=0)),
                ('segundos_assistidos_total', models.PositiveIntegerField(default=0)),
                ('concluido', models.BooleanField(default=False)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('marcou_conteudo_estudado', models.BooleanField(default=False)),
                ('iniciado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressos_video', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progressos', to='videos.videoconteudo')),
            ],
            options={
                'verbose_name': 'progresso em vídeo',
                'verbose_name_plural': 'progressos em vídeos',
            },
        ),
        migrations.AddIndex(
            model_name='videoconteudo',
            index=models.Index(fields=['conteudo', 'ativo', 'ordem'], name='videos_vide_conteud_5fb01a_idx'),
        ),
        migrations.AddConstraint(
            model_name='videoconteudo',
            constraint=models.UniqueConstraint(fields=('conteudo', 'youtube_id'), name='unique_video_por_conteudo'),
        ),
        migrations.AddIndex(
            model_name='sessaovideo',
            index=models.Index(fields=['usuario', '-iniciado_em'], name='videos_sess_usuario_94be15_idx'),
        ),
        migrations.AddIndex(
            model_name='progressovideo',
            index=models.Index(fields=['usuario', '-atualizado_em'], name='videos_prog_usuario_73e49e_idx'),
        ),
        migrations.AddConstraint(
            model_name='progressovideo',
            constraint=models.UniqueConstraint(fields=('usuario', 'video'), name='unique_progresso_usuario_video'),
        ),
    ]
