# Generated by Django 6.0.7 on 2026-10-03 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressovideo',
            name='concluido',
        ),
        migrations.RemoveField(
            model_name='progressovideo',
            name='concluido_em',
        ),
        migrations.RemoveField(
            model_name='progressovideo',
            name='marcou_conteudo_estudado',
        ),
        migrations.RemoveField(
            model_name='progressovideo',
            name='percentual',
        ),
        migrations.RemoveField(
            model_name='progressovideo',
            name='segmentos_assistidos',
        ),
        migrations.RemoveField(
            model_name='sessaovideo',
            name='percentual_video',
        ),
        migrations.RemoveField(
            model_name='videoconteudo',
            name='duracao_segundos',
        ),
    ]
