# Generated by Django 6.0.7 on 2026-08-16 13:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculo', '0003_conteudo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('enunciado', models.TextField()),
                ('explicacao', models.TextField(blank=True)),
                ('dificuldade', models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Média'), ('hard', 'Difícil')], default='medium', max_length=16)),
                ('tipo_fonte', models.CharField(choices=[('original', 'Original'), ('enem', 'ENEM'), ('vestibular', 'Vestibular'), ('adapted', 'Adaptada'), ('other', 'Outra')], default='original', max_length=16)),
                ('fonte_nome', models.CharField(blank=True, max_length=120)),
                ('fonte_ano', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fonte_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicada'), ('archived', 'Arquivada')], default='draft', max_length=16)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questoes', to='curriculo.materia')),
            ],
            options={
                'verbose_name': 'questão',
                'verbose_name_plural': 'questões',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chave', models.CharField(max_length=4)),
                ('texto', models.TextField()),
                ('correta', models.BooleanField(default=False)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='questoes.questao')),
            ],
            options={
                'verbose_name': 'alternativa',
                'verbose_name_plural': 'alternativas',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='QuestaoConteudo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('principal', models.BooleanField(default=False)),
                ('conteudo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questao_conteudos', to='curriculo.conteudo')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questao_conteudos', to='questoes.questao')),
            ],
            options={
                'verbose_name': 'conteúdo da questão',
                'verbose_name_plural': 'conteúdos da questão',
            },
        ),
        migrations.CreateModel(
            name='RespostaQuestao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('correta', models.BooleanField()),
                ('respondida_em', models.DateTimeField(auto_now_add=True)),
                ('alternativa_escolhida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas_recebidas', to='questoes.alternativa')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas', to='questoes.questao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_questoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'resposta de questão',
                'verbose_name_plural': 'respostas de questões',
                'ordering': ['-respondida_em'],
            },
        ),
        migrations.AddIndex(
            model_name='questao',
            index=models.Index(fields=['status', 'dificuldade'], name='questoes_qu_status_a62b18_idx'),
        ),
        migrations.AddIndex(
            model_name='questao',
            index=models.Index(fields=['materia', 'status'], name='questoes_qu_materia_be846a_idx'),
        ),
        migrations.AddConstraint(
            model_name='alternativa',
            constraint=models.UniqueConstraint(fields=('questao', 'chave'), name='unique_alternativa_chave_por_questao'),
        ),
        migrations.AddConstraint(
            model_name='alternativa',
            constraint=models.UniqueConstraint(fields=('questao', 'ordem'), name='unique_alternativa_ordem_por_questao'),
        ),
        migrations.AddConstraint(
            model_name='questaoconteudo',
            constraint=models.UniqueConstraint(fields=('questao', 'conteudo'), name='unique_conteudo_por_questao'),
        ),
        migrations.AddConstraint(
            model_name='questaoconteudo',
            constraint=models.UniqueConstraint(condition=models.Q(('principal', True)), fields=('questao',), name='unique_conteudo_principal_por_questao'),
        ),
        migrations.AddIndex(
            model_name='respostaquestao',
            index=models.Index(fields=['usuario', '-respondida_em'], name='questoes_re_usuario_dd00cd_idx'),
        ),
        migrations.AddIndex(
            model_name='respostaquestao',
            index=models.Index(fields=['questao', '-respondida_em'], name='questoes_re_questao_99fdff_idx'),
        ),
    ]
