# Generated by Django 6.0.7 on 2026-08-16 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0001_initial'),
    ]

    operations = [
    ]
