# Generated by Django 6.0.7 on 2026-08-24 16:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculo', '0004_povoar_conteudo_matematica'),
        ('questoes', '0002_povoar_questao_matematica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestaoSimulado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origem', models.CharField(choices=[('BANCO', 'Banco de questões'), ('MANUAL', 'Criada no simulado'), ('JSON', 'Importada por JSON')], default='MANUAL', max_length=12)),
                ('codigo_origem', models.CharField(blank=True, max_length=40)),
                ('enunciado', models.TextField()),
                ('explicacao', models.TextField(blank=True)),
                ('dificuldade', models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Média'), ('hard', 'Difícil')], default='medium', max_length=16)),
                ('tipo_fonte', models.CharField(choices=[('original', 'Original'), ('enem', 'ENEM'), ('vestibular', 'Vestibular'), ('adapted', 'Adaptada'), ('other', 'Outra')], default='original', max_length=16)),
                ('fonte_nome', models.CharField(blank=True, max_length=120)),
                ('fonte_ano', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fonte_url', models.URLField(blank=True)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('questao_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots_simulados', to='questoes.questao')),
            ],
            options={
                'verbose_name': 'questão do simulado',
                'verbose_name_plural': 'questões do simulado',
                'ordering': ['ordem', 'criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AlternativaSimulado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chave', models.CharField(max_length=4)),
                ('texto', models.TextField()),
                ('correta', models.BooleanField(default=False)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('questao_simulado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='simulados.questaosimulado')),
            ],
            options={
                'verbose_name': 'alternativa do simulado',
                'verbose_name_plural': 'alternativas do simulado',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='QuestaoSimuladoConteudo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('principal', models.BooleanField(default=False)),
                ('conteudo_titulo', models.CharField(max_length=160)),
                ('conteudo_slug', models.SlugField(max_length=100)),
                ('materia_nome', models.CharField(max_length=80)),
                ('conteudo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questoes_simulado', to='curriculo.conteudo')),
                ('questao_simulado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteudos', to='simulados.questaosimulado')),
            ],
            options={
                'verbose_name': 'conteúdo da questão do simulado',
                'verbose_name_plural': 'conteúdos da questão do simulado',
            },
        ),
        migrations.CreateModel(
            name='Simulado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('GERAL', 'Geral'), ('POR_MATERIA', 'Por matéria')], default='GERAL', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('archived', 'Arquivado')], default='draft', max_length=16)),
                ('tempo_limite', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ordem_exibicao', models.PositiveSmallIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('publicado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulados_criados', to=settings.AUTH_USER_MODEL)),
                ('materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='simulados', to='curriculo.materia')),
            ],
            options={
                'verbose_name': 'simulado',
                'verbose_name_plural': 'simulados',
                'ordering': ['ordem_exibicao', 'titulo'],
            },
        ),
        migrations.AddField(
            model_name='questaosimulado',
            name='simulado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='simulados.simulado'),
        ),
        migrations.CreateModel(
            name='TentativaSimulado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iniciada_em', models.DateTimeField(auto_now_add=True)),
                ('finalizada_em', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'Em andamento'), ('finished', 'Finalizada'), ('cancelled', 'Cancelada')], default='in_progress', max_length=16)),
                ('total_questoes', models.PositiveSmallIntegerField(default=0)),
                ('total_acertos', models.PositiveSmallIntegerField(default=0)),
                ('percentual', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tempo_gasto', models.DurationField(blank=True, null=True)),
                ('simulado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tentativas', to='simulados.simulado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentativas_simulados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tentativa de simulado',
                'verbose_name_plural': 'tentativas de simulado',
                'ordering': ['-iniciada_em'],
            },
        ),
        migrations.CreateModel(
            name='RespostaSimulado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alternativa_chave', models.CharField(max_length=4)),
                ('alternativa_texto', models.TextField()),
                ('correta', models.BooleanField(default=False)),
                ('respondida_em', models.DateTimeField(auto_now=True)),
                ('alternativa_escolhida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas', to='simulados.alternativasimulado')),
                ('questao_simulado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas', to='simulados.questaosimulado')),
                ('tentativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='simulados.tentativasimulado')),
            ],
            options={
                'verbose_name': 'resposta de simulado',
                'verbose_name_plural': 'respostas de simulado',
                'ordering': ['questao_simulado__ordem'],
            },
        ),
        migrations.AddConstraint(
            model_name='alternativasimulado',
            constraint=models.UniqueConstraint(fields=('questao_simulado', 'chave'), name='unique_alternativa_simulado_chave'),
        ),
        migrations.AddConstraint(
            model_name='alternativasimulado',
            constraint=models.UniqueConstraint(fields=('questao_simulado', 'ordem'), name='unique_alternativa_simulado_ordem'),
        ),
        migrations.AddConstraint(
            model_name='alternativasimulado',
            constraint=models.UniqueConstraint(condition=models.Q(('correta', True)), fields=('questao_simulado',), name='unique_alternativa_correta_simulado'),
        ),
        migrations.AddConstraint(
            model_name='questaosimuladoconteudo',
            constraint=models.UniqueConstraint(fields=('questao_simulado', 'conteudo'), name='unique_conteudo_questao_simulado'),
        ),
        migrations.AddConstraint(
            model_name='questaosimuladoconteudo',
            constraint=models.UniqueConstraint(condition=models.Q(('principal', True)), fields=('questao_simulado',), name='unique_conteudo_principal_questao_simulado'),
        ),
        migrations.AddIndex(
            model_name='simulado',
            index=models.Index(fields=['status', 'tipo', 'ordem_exibicao'], name='simulados_s_status_9f9f89_idx'),
        ),
        migrations.AddIndex(
            model_name='simulado',
            index=models.Index(fields=['materia', 'status'], name='simulados_s_materia_c7b26a_idx'),
        ),
        migrations.AddConstraint(
            model_name='questaosimulado',
            constraint=models.UniqueConstraint(fields=('simulado', 'ordem'), name='unique_questao_simulado_ordem'),
        ),
        migrations.AddIndex(
            model_name='tentativasimulado',
            index=models.Index(fields=['usuario', '-iniciada_em'], name='simulados_t_usuario_0f2b1c_idx'),
        ),
        migrations.AddIndex(
            model_name='tentativasimulado',
            index=models.Index(fields=['simulado', '-iniciada_em'], name='simulados_t_simulad_780a81_idx'),
        ),
        migrations.AddConstraint(
            model_name='respostasimulado',
            constraint=models.UniqueConstraint(fields=('tentativa', 'questao_simulado'), name='unique_resposta_por_questao_tentativa'),
        ),
    ]
