# Generated by Django 6.0.7 on 2026-09-05 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternativasimulado',
            name='imagem_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='alternativasimulado',
            name='imagem_public_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='questaosimulado',
            name='imagem_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='questaosimulado',
            name='imagem_public_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='alternativasimulado',
            name='texto',
            field=models.TextField(blank=True),
        ),
    ]
