# Generated by Django 6.0.7 on 2026-07-23 21:47

import django.db.models.deletion
import django.utils.timezone
import usuarios.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('anonimizado_em', models.DateTimeField(blank=True, null=True, verbose_name='anonimizado em')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
                'db_table': 'usuarios_usuario',
            },
            managers=[
                ('objects', usuarios.models.GerenciadorUsuario()),
            ],
        ),
        migrations.CreateModel(
            name='PerfilEstudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido_ranking', models.CharField(blank=True, max_length=50)),
                ('etapa_escolar', models.CharField(blank=True, choices=[('primeiro_ano', '1º ano do Ensino Médio'), ('segundo_ano', '2º ano do Ensino Médio'), ('terceiro_ano', '3º ano do Ensino Médio'), ('cursinho', 'Cursinho'), ('outro', 'Outro')], max_length=20)),
                ('fuso_horario', models.CharField(default='America/Bahia', max_length=64)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_estudante', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil de estudante',
                'verbose_name_plural': 'perfis de estudantes',
                'db_table': 'usuarios_perfil_estudante',
            },
        ),
        migrations.CreateModel(
            name='PreferenciaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exibir_ranking_publico', models.BooleanField(default=False)),
                ('permitir_percentil_privado', models.BooleanField(default=True)),
                ('notificacoes_email', models.BooleanField(default=True)),
                ('dificuldade_preferida', models.CharField(choices=[('facil', 'Fácil'), ('media', 'Média'), ('dificil', 'Difícil'), ('adaptativa', 'Adaptativa')], default='adaptativa', max_length=20)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'preferência de usuário',
                'verbose_name_plural': 'preferências de usuários',
                'db_table': 'usuarios_preferencia_usuario',
            },
        ),
        migrations.CreateModel(
            name='ConsentimentoPrivacidade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('termos', 'Termos de uso'), ('privacidade', 'Política de privacidade'), ('ranking', 'Ranking'), ('ia', 'Inteligência artificial')], max_length=20)),
                ('versao_documento', models.CharField(max_length=30)),
                ('aceito', models.BooleanField(default=False)),
                ('registrado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('ip_hash', models.CharField(blank=True, max_length=128)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimentos_privacidade', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'consentimento de privacidade',
                'verbose_name_plural': 'consentimentos de privacidade',
                'db_table': 'usuarios_consentimento_privacidade',
                'ordering': ['-registrado_em'],
                'indexes': [models.Index(fields=['usuario', 'tipo_documento', '-registrado_em'], name='consent_usuario_tipo_idx'), models.Index(fields=['tipo_documento', 'versao_documento'], name='consent_doc_versao_idx')],
            },
        ),
    ]
