# Generated by Django 6.0.7 on 2026-08-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilestudante',
            name='apelido_ranking',
        ),
        migrations.RemoveField(
            model_name='perfilestudante',
            name='fuso_horario',
        ),
        migrations.AlterField(
            model_name='consentimentoprivacidade',
            name='tipo_documento',
            field=models.CharField(choices=[('termos', 'Termos de uso'), ('privacidade', 'Política de privacidade')], max_length=20),
        ),
        migrations.DeleteModel(
            name='PreferenciaUsuario',
        ),
    ]
