# Generated by Django 6.0.7 on 2026-08-01 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_perfilestudante_apelido_ranking_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='consentimentoprivacidade',
            name='consent_usuario_tipo_idx',
        ),
        migrations.RemoveIndex(
            model_name='consentimentoprivacidade',
            name='consent_doc_versao_idx',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='anonimizado_em',
        ),
        migrations.DeleteModel(
            name='ConsentimentoPrivacidade',
        ),
    ]
