# Generated by Django 6.0.7 on 2026-08-16 15:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculo', '0003_conteudo'),
        ('questoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConteudoEstudado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('marcado_em', models.DateTimeField(auto_now_add=True)),
                ('conteudo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marcacoes_estudado', to='curriculo.conteudo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteudos_estudados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'conteúdo estudado',
                'verbose_name_plural': 'conteúdos estudados',
                'ordering': ['-marcado_em'],
                'indexes': [models.Index(fields=['usuario', '-marcado_em'], name='estudos_con_usuario_0a21e6_idx')],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'conteudo'), name='unique_conteudo_estudado_usuario_conteudo')],
            },
        ),
        migrations.CreateModel(
            name='ItemMinhaLista',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adicionado_em', models.DateTimeField(auto_now_add=True)),
                ('conteudo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_minha_lista', to='curriculo.conteudo')),
                ('materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_minha_lista', to='curriculo.materia')),
                ('questao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_minha_lista', to='questoes.questao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_minha_lista', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'item da Minha Lista',
                'verbose_name_plural': 'itens da Minha Lista',
                'ordering': ['-adicionado_em'],
                'indexes': [models.Index(fields=['usuario', '-adicionado_em'], name='estudos_ite_usuario_1c060a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('materia__isnull', False), ('conteudo__isnull', True), ('questao__isnull', True)), models.Q(('materia__isnull', True), ('conteudo__isnull', False), ('questao__isnull', True)), models.Q(('materia__isnull', True), ('conteudo__isnull', True), ('questao__isnull', False)), _connector='OR'), name='item_minha_lista_exatamente_um_alvo'), models.UniqueConstraint(condition=models.Q(('materia__isnull', False)), fields=('usuario', 'materia'), name='unique_minha_lista_usuario_materia'), models.UniqueConstraint(condition=models.Q(('conteudo__isnull', False)), fields=('usuario', 'conteudo'), name='unique_minha_lista_usuario_conteudo'), models.UniqueConstraint(condition=models.Q(('questao__isnull', False)), fields=('usuario', 'questao'), name='unique_minha_lista_usuario_questao')],
            },
        ),
    ]
