# Generated by Django 6.0.7 on 2026-08-24 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='itemminhalista',
            name='item_minha_lista_exatamente_um_alvo',
        ),
    ]
