# Generated by Django 6.0.7 on 2026-08-24 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0004_povoar_conteudo_matematica'),
        ('estudos', '0002_remove_itemminhalista_item_minha_lista_exatamente_um_alvo'),
        ('questoes', '0002_povoar_questao_matematica'),
        ('simulados', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itemminhalista',
            name='simulado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_minha_lista', to='simulados.simulado'),
        ),
        migrations.AddConstraint(
            model_name='itemminhalista',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('materia__isnull', False), ('conteudo__isnull', True), ('questao__isnull', True), ('simulado__isnull', True)), models.Q(('materia__isnull', True), ('conteudo__isnull', False), ('questao__isnull', True), ('simulado__isnull', True)), models.Q(('materia__isnull', True), ('conteudo__isnull', True), ('questao__isnull', False), ('simulado__isnull', True)), models.Q(('materia__isnull', True), ('conteudo__isnull', True), ('questao__isnull', True), ('simulado__isnull', False)), _connector='OR'), name='item_minha_lista_exatamente_um_alvo'),
        ),
        migrations.AddConstraint(
            model_name='itemminhalista',
            constraint=models.UniqueConstraint(condition=models.Q(('simulado__isnull', False)), fields=('usuario', 'simulado'), name='unique_minha_lista_usuario_simulado'),
        ),
    ]
