# Generated by Django 6.0.7 on 2026-08-16 01:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('ordem_exibicao', models.PositiveSmallIntegerField(default=0)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='materias_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'matéria',
                'verbose_name_plural': 'matérias',
                'ordering': ['ordem_exibicao', 'nome'],
                'indexes': [models.Index(fields=['ativa', 'ordem_exibicao'], name='curriculo_m_ativa_91ef21_idx')],
            },
        ),
    ]
