# Generated by Django 6.0.7 on 2026-08-16 01:29

from django.db import migrations


def criar_materias_iniciais(apps, schema_editor):
    Materia = apps.get_model("curriculo", "Materia")
    materias = [
        {
            "nome": "Matemática",
            "slug": "matematica",
            "descricao": "Disciplina inicial para estudos de matemática.",
            "ordem_exibicao": 1,
        },
        {
            "nome": "Física",
            "slug": "fisica",
            "descricao": "Disciplina inicial para estudos de física.",
            "ordem_exibicao": 2,
        },
        {
            "nome": "Química",
            "slug": "quimica",
            "descricao": "Disciplina inicial para estudos de química.",
            "ordem_exibicao": 3,
        },
    ]

    for dados in materias:
        Materia.objects.get_or_create(
            slug=dados["slug"],
            defaults={
                "nome": dados["nome"],
                "descricao": dados["descricao"],
                "ordem_exibicao": dados["ordem_exibicao"],
                "ativa": True,
                "criado_por": None,
            },
        )


def remover_materias_iniciais(apps, schema_editor):
    Materia = apps.get_model("curriculo", "Materia")
    Materia.objects.filter(
        slug__in=["matematica", "fisica", "quimica"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(criar_materias_iniciais,
                             remover_materias_iniciais),
    ]
