# Generated by Django 6.0.7 on 2026-08-16 13:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0002_criar_materias_iniciais'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conteudo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('titulo', models.CharField(max_length=160)),
                ('resumo', models.TextField()),
                ('texto_estudo', models.TextField(blank=True)),
                ('dificuldade', models.CharField(choices=[('basic', 'Básico'), ('intermediate', 'Intermediário'), ('advanced', 'Avançado')], default='basic', max_length=16)),
                ('ordem_sugerida', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('archived', 'Arquivado')], default='draft', max_length=16)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conteudos_criados', to=settings.AUTH_USER_MODEL)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conteudos', to='curriculo.materia')),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subconteudos', to='curriculo.conteudo')),
            ],
            options={
                'verbose_name': 'conteúdo',
                'verbose_name_plural': 'conteúdos',
                'ordering': ['ordem_sugerida', 'titulo'],
                'indexes': [models.Index(fields=['status', 'ordem_sugerida'], name='curriculo_c_status_b39f66_idx'), models.Index(fields=['materia', 'status', 'ordem_sugerida'], name='curriculo_c_materia_5d8315_idx')],
                'constraints': [models.UniqueConstraint(fields=('materia', 'slug'), name='unique_conteudo_slug_por_materia')],
            },
        ),
    ]
